apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-pass
    literals:
      - password=YWRtaW4K
resources:
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/wordpress_deployment_files/mysql-deployment.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/wordpress_deployment_files/wordpress-deployment.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/wordpress_deployment_files/local-volumes.yaml
